# -*- coding: utf-8 -*-
"""PYTHON KNOWLEDGE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tf4zazNMoJUX__jcA1etg3omw2H_EXIL
"""

# ABOUT PANDAS LIBRARY

import pandas as pd

'''Sometimes when you run a file if you have a big output 
the output will not be shown entirely, therefore in orgder
to be able to see the entire output after the part that you are
importing all your libraries you should run the following command'''

pd.set_option('display.max_rows', None)

